### PR TITLE
Feat/#124 contact maps

### PR DESCRIPTION
**Pull request by Mani-sub**
To test
- Pull the branch local and run the application.
- Navigate to contact page, SUB open maps will be loaded.

### CODE REVIEW

**Comment by joschrew** [comment]
Where did you get the maps? The GWDG building on the map is the old one and does not match the provided Address. And after opening the map/application manually it says: no further development.

For SUB I found this: https://www.sub.uni-goettingen.de/standorte-raumangebote/standorte-mit-oeffnungszeiten/zentralbibliothek/
and for GDWG this: https://www.gwdg.de/web/guest/about-us/contact.
But I don't know how to get the JavaScript to display the maps.

**Comment by Mani-sub** [comment]
> Where did you get the maps? The GWDG building on the map is the old one and does not match the provided address. And after opening the map/application manually it says: no further development.
> 
> For SUB I found this: https://www.sub.uni-goettingen.de/standorte-raumangebote/standorte-mit-oeffnungszeiten/zentralbibliothek/ and for GDWG this: https://www.gwdg.de/web/guest/about-us/contact. But I don't know how to get the JavaScript to display the maps.

Both maps are from the Geodata of university - https://www.geodata.uni-goettingen.de/lageplan/
- SUB it's the same central library building, not sure what you mean by different address.
- GWDG - when i search for it, it still shows the same building.

**Comment by joschrew** [comment]
With "where did you get the maps" I wanted to ask if someone told you to use it or if you just choose it yourself. But I think the latter is true.
With the address I meant GWDG. The GWDG-building on the map is the old one at Faßberg, but GWDG left that building and is now at Burckardtweg 4, but that new building (new build last year) is not available at https://www.geodata.uni-goettingen.de. I think this map maybe is not maintained any more.
Because of that I think what should be used is something like the links I provided. But maybe someone else could provide examples of maps which should be used.

**Comment by Mani-sub** [comment]
> With "where did you get the maps" I wanted to ask if someone told you to use it or if you just choose it yourself. But I think the latter is true. With the address I meant GWDG. The GWDG-building on the map is the old one at Faßberg, but GWDG left that building and is now at Burckardtweg 4, but that new building (new build last year) is not available at https://www.geodata.uni-goettingen.de. I think this map maybe is not maintained any more. Because of that I think what should be used is something like the links I provided. But maybe someone else could provide examples of maps which should be used.

Yes, i have got the maps entry point which are commented on the issue ticket [issue-124](https://pm.sub.uni-goettingen.de/browse/OLAHDS-124) and i have used the same. 

Yes, looks like the GWDG building was moved to a different location but the geo-uni maps weren’t updated. I will try to talk with Lilja and update the PR accordingly !!

**Pull request merged**
