### PR TITLE
feat: Implementation of basic search list with pagination.

### PR DESCRIPTION
**Pull request by Mani-sub**
- Pull the branch into local for testing.
- run `yarn install` then `yarn serve`.
- Change the backend `baseUrl` inside `src/services/lzaApi.ts` line 4 to `http://localhost:9200` (port running one backend application).
- Once the application loads, try to search for any term (ex: Berlin).

- The basic search list can be viewed and try to select on any item - we can navigate to Detailed page with basic information.
- There is an expanded button to view additional details.

To run tests:

- run the application `yarn serve` the application loads on `http://localhost:8080`.
- If the application loads on a different port then modify the baseUrl inside `cypress.config.ts`.
- On a new terminal run `yarn cypress` and the basic tests run.

### CODE REVIEW

**Comment by joschrew** [comment]
I like that you added tests. Maybe they can be used for ci/cd pipeline at one point in the future.
I tried to get the tests to fail but didn't succeed. For example in `cypress/e2e/search.cy.ts` in the first test (`Should display search header`) I replaced `#search-header` with `not-there-123` and the tests still pass. Or I tried to replace `/home` with `not-there`. Do you know what do I have to do to make a test fail?

**Comment by Mani-sub** [comment]
> I like that you added tests. Maybe they can be used for ci/cd pipeline at one point in the future. I tried to get the tests to fail but didn't succeed. For example in `cypress/e2e/search.cy.ts` in the first test (`Should display search header`) I replaced `#search-header` with `not-there-123` and the tests still pass. Or I tried to replace `/home` with `not-there`. Do you know what do I have to do to make a test fail?

Thank you for testing, i will look into it and update the PR soon.

**Comment by joschrew** [comment]
Hi, last week I added search-endpoints to our backend for this PR. I added one commit to this PR to use this endpoints for the searching implemented in this PR. To test it, change the backend `baseUrl` inside `src/services/lzaApi.ts` line 4 to http://141.5.99.53/api (works only if you are in GÖNET).

**Review by joschrew — APPROVED** [review]
lgtm

**Pull request merged**
